language: cpp
dist: trusty
os: linux
addons:
  apt:
    packages:
      - valgrind
      - g++-7
    sources: &sources
      - ubuntu-toolchain-r-test

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/src/
    - ${TRAVIS_BUILD_DIR}/test/

script:
      - mkdir build
      - cd build
      - CXX=/usr/bin/g++-7 C=/usr/bin/gcc-7 cmake ..
      - ls -l ../
      - make all

after_success:
        - echo "success"

after_failure:
        - echo "failure"        