language: cpp
dist: trusty
os: linux
addons:
  apt:
    packages:
      - valgrind
      - g++-7
    sources: &sources
      - ubuntu-toolchain-r-test

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/lib/
    - ${TRAVIS_BUILD_DIR}/src/
    - ${TRAVIS_BUILD_DIR}/test/

script:
      - mkdir build
      - cd build
      - CXX=/usr/bin/g++-7 C=/usr/bin/gcc-7 cmake ..
      - mkdir lib
      - cd lib
      - git clone https://github.com/google/googletest/
      - cd ..
      - ls -l
      - ls -l lib/googletest/googletest/include/gtest
      - make all
      - ./test/reverse_string_test

after_success:
        - echo "success"

after_failure:
        - echo "failure"        