language: cpp
dist: trusty
os: linux
addons:
  apt:
    packages:
      - valgring
      - cmake
      - g++-7
      - clang11
    sources:
      - ubuntu-toolchain-r-test

cache:
  - bundler
  directories:
    - ${TRAVIS_BUILD_DIR}/lib/googletest
    - ${TRAVIS_BUILD_DIR}/src/
    - ${TRAVIS_BUILD_DIR}/test/

script:
      - mkdir build
      - cd build
      - CXX=/usr/bin/g++-7 C=/usr/bin/gcc-7 cmake ..
      - make all
      - ./test/reverse_string_test

after_success:
        - echo "success"

after_failure:
        - echo "failure"        